sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ozcanmelih/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ozcanmelih/react-test npm test

after_success:
  - docker build -t ozcanmelih/multi-client ./client
  - docker build -t ozcanmelih/multi-nginx ./nginx
  - docker build -t ozcanmelih/multi-server ./server
  - docker build -t ozcanmelih/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ozcanmelih/multi-client
  - docker push ozcanmelih/multi-nginx
  - docker push ozcanmelih/multi-server
  - docker push ozcanmelih/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-012285672160"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY